import { Request, Response } from 'express';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit'; // Fixed: default import
import { DateTime } from 'luxon';
import { lookupTenantDatabase, safeTenantExecute, safeTenantQuery } from '../../shared/dbConfig';

interface TenantRequest extends Request {
    tenantSlug?: string;
}

const nowNairobi = (): string => {
    return DateTime.now().setZone('Africa/Nairobi').toFormat('yyyy-MM-dd HH:mm:ss');
};

const formatFacilityName = (tenantSlug: string): string => {
    if (!tenantSlug || tenantSlug === 'system_shared') return 'RestPoint Mortuary';

    return tenantSlug
        .replace(/[-_]/g, ' ')
        .split(' ')
        .filter(Boolean)
        .map((token) => token.charAt(0).toUpperCase() + token.slice(1).toLowerCase())
        .join(' ');
};

const getFacilityLogoPath = (tenantSlug: string): string => {
    return path.join(__dirname, '../../public/logo', `${tenantSlug}.png`);
};

const drawPdfHeader = (doc: any, facilityName: string, tenantSlug: string): void => {
    const logoPath = getFacilityLogoPath(tenantSlug);
    const headerY = 40;

    if (fs.existsSync(logoPath)) {
        doc.image(logoPath, 50, headerY, { width: 90 });
    } else {
        doc
            .rect(50, headerY, 90, 45)
            .fill('#ffffff')
            .stroke('#e5e7eb');
        doc
            .font('Helvetica-Bold')
            .fontSize(14)
            .fillColor('#1f2937')
            .text(facilityName, 55, headerY + 10, { width: 80, align: 'center' });
    }

    doc
        .font('Helvetica-Bold')
        .fontSize(18)
        .fillColor('#111827')
        .text('Postmortem / Autopsy Report', 160, headerY + 8, { align: 'left' });

    doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor('#4b5563')
        .text(`Facility: ${facilityName}`, 160, headerY + 34)
        .text(`Generated: ${DateTime.now().setZone('Africa/Nairobi').toFormat('dd LLL yyyy, HH:mm')}`, 160, headerY + 48);

    doc.moveTo(50, headerY + 75).lineTo(545, headerY + 75).stroke('#e5e7eb');
};

const drawPdfFooter = (doc: any): void => {
    const bottom = doc.page.height - 50;
    doc.moveTo(50, bottom - 15).lineTo(545, bottom - 15).stroke('#e5e7eb');
    doc
        .font('Helvetica')
        .fontSize(8)
        .fillColor('#6b7280')
        .text('Generated by RestPoint Mortuary Management', 50, bottom, {
            align: 'left'
        });
};

const ensurePdfLayout = (doc: any, facilityName: string, tenantSlug: string): void => {
    drawPdfHeader(doc, facilityName, tenantSlug);
    drawPdfFooter(doc);
    doc.on('pageAdded', () => {
        drawPdfHeader(doc, facilityName, tenantSlug);
        drawPdfFooter(doc);
        doc.moveDown();
    });
};

// Ensure postmortem table exists
const ensurePostmortemTable = async (dbName: string): Promise<void> => {
    const createTableSQL = `
        CREATE TABLE IF NOT EXISTS postmortem (
            id INT AUTO_INCREMENT PRIMARY KEY,
            deceased_id VARCHAR(100) NOT NULL,
            pathologist_name VARCHAR(255),
            external_pathologist_name VARCHAR(255),
            external_pathologist_mobile VARCHAR(20),
            external_pathologist_id VARCHAR(50),
            examination_summary TEXT,
            cause_of_death TEXT,
            immediate_cause_of_death TEXT,
            underlying_cause_of_death TEXT,
            contributing_conditions TEXT,
            manner_of_death VARCHAR(50),
            requesting_authority VARCHAR(100),
            findings JSON,
            head_findings TEXT,
            chest_findings TEXT,
            abdomen_findings TEXT,
            extremities_findings TEXT,
            toxicology_findings TEXT,
            custom_findings JSON,
            report_pdf_url VARCHAR(500),
            staff_username VARCHAR(255),
            mortuary_name VARCHAR(255),
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            created_by INT,
            updated_by INT,
            FOREIGN KEY (deceased_id) REFERENCES deceased(deceased_id) ON DELETE CASCADE,
            INDEX idx_deceased_id (deceased_id),
            INDEX idx_created_at (created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
    `;
    
    try {
        await safeTenantExecute(dbName, createTableSQL, []);
        console.log(`✅ Postmortem table ensured for database: ${dbName}`);
    } catch (error) {
        console.error(`❌ Failed to create postmortem table:`, error);
        throw error;
    }
};

/**
 * Save postmortem examination data
 * POST /api/v1/restpoint/deceased/postmortem/save
 */
export const savePostmortem = async (req: TenantRequest, res: Response): Promise<Response> => {
    const tenantSlug = req.headers['x-tenant-slug'] as string || req.tenantSlug;

    if (!tenantSlug || tenantSlug === 'system_shared') {
        return res.status(400).json({
            success: false,
            message: 'Valid tenant required. Please provide x-tenant-slug header'
        });
    }

    try {
        const {
            deceased_id,
            pathologist_name,
            external_pathologist_name,
            external_pathologist_mobile,
            external_pathologist_id,
            examination_summary,
            cause_of_death,
            immediate_cause_of_death,
            underlying_cause_of_death,
            contributing_conditions,
            manner_of_death,
            requesting_authority,
            findings
        } = req.body;

        if (!deceased_id) {
            return res.status(400).json({
                success: false,
                message: 'deceased_id is required'
            });
        }

        console.log(`📝 Saving postmortem data for deceased: ${deceased_id}`);
        const dbName = await lookupTenantDatabase(tenantSlug);

        if (!dbName) {
            return res.status(404).json({
                success: false,
                message: `No database configured for tenant: ${tenantSlug}`
            });
        }

        await ensurePostmortemTable(dbName);

        // Check if postmortem record already exists
        const existingQuery = 'SELECT id FROM postmortem WHERE deceased_id = ?';
        const existing = await safeTenantQuery(dbName, existingQuery, [deceased_id]);

        const now = nowNairobi();

        if (existing && (existing as any[]).length > 0) {
            // Update existing record
            const updateQuery = `
                UPDATE postmortem SET
                    pathologist_name = ?,
                    external_pathologist_name = ?,
                    external_pathologist_mobile = ?,
                    external_pathologist_id = ?,
                    examination_summary = ?,
                    cause_of_death = ?,
                    immediate_cause_of_death = ?,
                    underlying_cause_of_death = ?,
                    contributing_conditions = ?,
                    manner_of_death = ?,
                    requesting_authority = ?,
                    findings = ?,
                    updated_at = ?
                WHERE deceased_id = ?
            `;

            await safeTenantExecute(dbName, updateQuery, [
                pathologist_name,
                external_pathologist_name,
                external_pathologist_mobile,
                external_pathologist_id,
                examination_summary,
                cause_of_death,
                immediate_cause_of_death,
                underlying_cause_of_death,
                contributing_conditions,
                manner_of_death,
                requesting_authority,
                typeof findings === 'string' ? findings : JSON.stringify(findings),
                now,
                deceased_id
            ]);

            console.log(`✅ Postmortem record updated for deceased: ${deceased_id}`);
            return res.status(200).json({
                success: true,
                message: 'Postmortem data saved successfully',
                data: { deceased_id }
            });
        } else {
            // Insert new record
            const insertQuery = `
                INSERT INTO postmortem (
                    deceased_id, pathologist_name, external_pathologist_name,
                    external_pathologist_mobile, external_pathologist_id,
                    examination_summary, cause_of_death, immediate_cause_of_death,
                    underlying_cause_of_death, contributing_conditions, manner_of_death,
                    requesting_authority, findings, created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            `;

            const result = await safeTenantExecute(dbName, insertQuery, [
                deceased_id,
                pathologist_name,
                external_pathologist_name,
                external_pathologist_mobile,
                external_pathologist_id,
                examination_summary,
                cause_of_death,
                immediate_cause_of_death,
                underlying_cause_of_death,
                contributing_conditions,
                manner_of_death,
                requesting_authority,
                typeof findings === 'string' ? findings : JSON.stringify(findings),
                now,
                now
            ]);

            console.log(`✅ Postmortem record created for deceased: ${deceased_id}`);
            return res.status(201).json({
                success: true,
                message: 'Postmortem data saved successfully',
                data: { id: (result as any).insertId, deceased_id }
            });
        }
    } catch (error: any) {
        console.error('❌ Error in savePostmortem:', error);
        return res.status(500).json({
            success: false,
            message: 'Internal Server Error',
            error: process.env.NODE_ENV === 'development' ? error.message : undefined
        });
    }
};


/**
 * Get postmortem data by deceased ID
 * GET /api/v1/restpoint/deceased/postmortem/:deceased_id
 */

export const getPostmortemByDeceasedId = async (req: TenantRequest, res: Response): Promise<Response> => {
    const tenantSlug = req.headers['x-tenant-slug'] as string || req.tenantSlug;
    const { deceased_id } = req.params;

    if (!deceased_id || !tenantSlug) {
        return res.status(400).json({
            success: false,
            message: 'deceased_id and tenant are required'
        });
    }

    try {
        const dbName = await lookupTenantDatabase(tenantSlug);
        if (!dbName) {
            return res.status(404).json({
                success: false,
                message: `No database configured for tenant: ${tenantSlug}`
            });
        }

        await ensurePostmortemTable(dbName);

        const selectQuery = `
            SELECT 
                id, deceased_id, pathologist_name, external_pathologist_name,
                external_pathologist_mobile, external_pathologist_id,
                examination_summary, cause_of_death, immediate_cause_of_death,
                underlying_cause_of_death, contributing_conditions, manner_of_death,
                requesting_authority, findings, report_pdf_url,
                created_at, updated_at
            FROM postmortem
            WHERE deceased_id = ?
        `;

        const records = await safeTenantQuery(dbName, selectQuery, [deceased_id]);

        if (!records || (records as any[]).length === 0) {
            return res.status(404).json({
                success: false,
                message: 'Postmortem record not found'
            });
        }

        const postmortem = (records as any[])[0];
        
        // Parse findings if it's JSON
        if (postmortem.findings && typeof postmortem.findings === 'string') {
            try {
                postmortem.findings = JSON.parse(postmortem.findings);
            } catch (e) {
                // Keep as is if not valid JSON
            }
        }

        return res.status(200).json({
            success: true,
            message: 'Postmortem record fetched successfully',
            data: postmortem
        });
    } catch (error: any) {
        console.error('❌ Error in getPostmortemByDeceasedId:', error);
        return res.status(500).json({
            success: false,
            message: 'Internal Server Error'
        });
    }
};

/**
 * Update postmortem record
 * PUT /api/v1/restpoint/deceased/postmortem/:id
 */
export const updatePostmortem = async (req: TenantRequest, res: Response): Promise<Response> => {
    const tenantSlug = req.headers['x-tenant-slug'] as string || req.tenantSlug;
    const { id } = req.params;

    if (!id || !tenantSlug) {
        return res.status(400).json({
            success: false,
            message: 'id and tenant are required'
        });
    }

    try {
        const dbName = await lookupTenantDatabase(tenantSlug);
        if (!dbName) {
            return res.status(404).json({
                success: false,
                message: `No database configured for tenant: ${tenantSlug}`
            });
        }

        const updates = req.body;
        const allowedFields = [
            'pathologist_name', 'external_pathologist_name', 'external_pathologist_mobile',
            'external_pathologist_id', 'examination_summary', 'cause_of_death',
            'immediate_cause_of_death', 'underlying_cause_of_death', 'contributing_conditions',
            'manner_of_death', 'requesting_authority', 'findings', 'report_pdf_url'
        ];

        const fields: string[] = [];
        const values: any[] = [];

        for (const field of allowedFields) {
            if (updates[field] !== undefined) {
                fields.push(`${field} = ?`);
                values.push(field === 'findings' && typeof updates[field] === 'object' 
                    ? JSON.stringify(updates[field])
                    : updates[field]);
            }
        }

        if (fields.length === 0) {
            return res.status(400).json({
                success: false,
                message: 'No fields to update'
            });
        }

        fields.push('updated_at = ?');
        values.push(nowNairobi());
        values.push(id);

        const updateQuery = `UPDATE postmortem SET ${fields.join(', ')} WHERE id = ?`;
        await safeTenantExecute(dbName, updateQuery, values);

        return res.status(200).json({
            success: true,
            message: 'Postmortem record updated successfully'
        });
    } catch (error: any) {
        console.error('❌ Error in updatePostmortem:', error);
        return res.status(500).json({
            success: false,
            message: 'Internal Server Error'
        });
    }
};

/**
 * Delete postmortem record
 * DELETE /api/v1/restpoint/deceased/postmortem/:id
 */
export const deletePostmortem = async (req: TenantRequest, res: Response): Promise<Response> => {
    const tenantSlug = req.headers['x-tenant-slug'] as string || req.tenantSlug;
    const { id } = req.params;

    if (!id || !tenantSlug) {
        return res.status(400).json({
            success: false,
            message: 'id and tenant are required'
        });
    }

    try {
        const dbName = await lookupTenantDatabase(tenantSlug);
        if (!dbName) {
            return res.status(404).json({
                success: false,
                message: `No database configured for tenant: ${tenantSlug}`
            });
        }

        const deleteQuery = 'DELETE FROM postmortem WHERE id = ?';
        await safeTenantExecute(dbName, deleteQuery, [id]);

        return res.status(200).json({
            success: true,
            message: 'Postmortem record deleted successfully'
        });
    } catch (error: any) {
        console.error('❌ Error in deletePostmortem:', error);
        return res.status(500).json({
            success: false,
            message: 'Internal Server Error'
        });
    }
};

/**
 * Generate postmortem PDF report
 * GET /api/v1/restpoint/deceased/postmortem/:deceased_id/pdf
 */
export const generatePostmortemPDF = async (req: TenantRequest, res: Response): Promise<void> => {
    const tenantSlug = req.headers['x-tenant-slug'] as string || req.tenantSlug;
    const { deceased_id } = req.params;

    if (!deceased_id || !tenantSlug) {
        res.status(400).json({
            success: false,
            message: 'deceased_id and tenant are required'
        });
        return;
    }

    try {
        const dbName = await lookupTenantDatabase(tenantSlug);
        if (!dbName) {
            res.status(404).json({
                success: false,
                message: `No database configured for tenant: ${tenantSlug}`
            });
            return;
        }

        // Fetch postmortem and deceased data
        const postmortemQuery = 'SELECT * FROM postmortem WHERE deceased_id = ?';
        const deceasedQuery = 'SELECT full_name, date_of_death FROM deceased WHERE deceased_id = ?';

        const postmortemResults = await safeTenantQuery(dbName, postmortemQuery, [deceased_id]);
        const deceasedResults = await safeTenantQuery(dbName, deceasedQuery, [deceased_id]);

        if (!postmortemResults || (postmortemResults as any[]).length === 0) {
            res.status(404).json({
                success: false,
                message: 'Postmortem record not found'
            });
            return;
        }

        const postmortem = (postmortemResults as any[])[0];
        const deceased = deceasedResults && (deceasedResults as any[]).length > 0 ? (deceasedResults as any[])[0] : null;

        const facilityName = formatFacilityName(tenantSlug);

        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        
        // Set response headers
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename="postmortem-${deceased_id}.pdf"`);

        // Pipe the PDF to the response
        doc.pipe(res);

        ensurePdfLayout(doc, facilityName, tenantSlug);

        doc.moveDown(4);
        doc
            .font('Helvetica-Bold')
            .fontSize(12)
            .fillColor('#111827')
            .text('Deceased Information', { underline: true });

        const deceasedName = deceased?.full_name || 'Unknown';
        const deceasedDateOfDeath = deceased?.date_of_death || 'Unknown';

        doc
            .font('Helvetica')
            .fontSize(10)
            .fillColor('#1f2937')
            .text(`Name: ${deceasedName}`)
            .text(`Deceased ID: ${deceased_id}`)
            .text(`Date of Death: ${deceasedDateOfDeath}`)
            .text(`Report Date: ${DateTime.now().setZone('Africa/Nairobi').toFormat('dd LLL yyyy')}`)
            .moveDown(1);

        doc
            .font('Helvetica-Bold')
            .fontSize(12)
            .text('Postmortem Summary', { underline: true });

        doc
            .font('Helvetica')
            .fontSize(10)
            .fillColor('#1f2937')
            .text(postmortem.examination_summary || 'No summary provided', {
                align: 'left',
                paragraphGap: 4,
                lineGap: 3
            })
            .moveDown(1);

        let displayFindings: Record<string, any> = {};
        if (postmortem.findings) {
            if (typeof postmortem.findings === 'string') {
                try {
                    displayFindings = JSON.parse(postmortem.findings || '{}');
                } catch {
                    displayFindings = { 'Findings': postmortem.findings };
                }
            } else {
                displayFindings = postmortem.findings;
            }
        }

        if (displayFindings && Object.keys(displayFindings).length > 0) {
            doc
                .font('Helvetica-Bold')
                .fontSize(12)
                .text('Findings', { underline: true })
                .moveDown(0.5);

            Object.entries(displayFindings).forEach(([title, description]) => {
                doc
                    .font('Helvetica-Bold')
                    .fontSize(10)
                    .fillColor('#111827')
                    .text(title || 'Finding', { continued: false });

                doc
                    .font('Helvetica')
                    .fontSize(10)
                    .fillColor('#1f2937')
                    .text(description || 'No description provided', {
                        indent: 10,
                        paragraphGap: 4,
                        lineGap: 2
                    })
                    .moveDown(0.5);
            });
        }

        doc
            .font('Helvetica-Bold')
            .fontSize(12)
            .text('Cause of Death Details', { underline: true })
            .moveDown(0.5);

        doc
            .font('Helvetica')
            .fontSize(10)
            .text(`Primary Cause: ${postmortem.cause_of_death || 'Not specified'}`)
            .text(`Immediate Cause: ${postmortem.immediate_cause_of_death || 'Not specified'}`)
            .text(`Underlying Cause: ${postmortem.underlying_cause_of_death || 'Not specified'}`)
            .text(`Contributing Conditions: ${postmortem.contributing_conditions || 'Not specified'}`)
            .text(`Manner of Death: ${postmortem.manner_of_death || 'Not specified'}`)
            .moveDown(1);

        doc
            .font('Helvetica-Bold')
            .fontSize(12)
            .text('Pathologist Information', { underline: true })
            .moveDown(0.5);

        const pathologistLabel = postmortem.external_pathologist_name ? 'External Pathologist' : 'Staff Pathologist';
        const pathologistName = postmortem.external_pathologist_name || postmortem.pathologist_name || 'Not specified';
        const externalId = postmortem.external_pathologist_id ? `ID: ${postmortem.external_pathologist_id}` : '';

        doc
            .font('Helvetica')
            .fontSize(10)
            .text(`${pathologistLabel}: ${pathologistName}`)
            .text(externalId)
            .text(`Contact: ${postmortem.external_pathologist_mobile || 'Not specified'}`)
            .text(`Requesting Authority: ${postmortem.requesting_authority || 'Not specified'}`)
            .moveDown(1);

        // Finalize the PDF
        doc.end();
    } catch (error: any) {
        console.error('❌ Error in generatePostmortemPDF:', error);
        // Only send error response if headers haven't been sent yet
        if (!res.headersSent) {
            res.status(500).json({
                success: false,
                message: 'Internal Server Error'
            });
        }
    }
};