services:
  socketio-service:
    build:
      context: .
      dockerfile: socketio-service/Dockerfile
    container_name: socketio-service
    ports:
      - "8010:8010"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./global:/usr/src/app/global
      - ./.env:/usr/src/app/.env
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: shared-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  default:
    name: siasa-network
    external: true