-- Create deceased table (NO tenant_slug needed - each tenant has their own DB)
CREATE TABLE IF NOT EXISTS deceased (
    id INT NOT NULL AUTO_INCREMENT,
    deceased_id VARCHAR(100) NOT NULL COMMENT 'Unique identifier',
    admission_number VARCHAR(100) NOT NULL UNIQUE,
    cause_of_death TEXT,
    date_admitted TIMESTAMP NULL,
    date_of_birth DATE NOT NULL,
    date_of_death TIMESTAMP NULL,
    date_registered TIMESTAMP NULL,
    full_name VARCHAR(255) NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    place_of_death VARCHAR(255) NOT NULL,
    county VARCHAR(100) NOT NULL,
    national_id VARCHAR(50) NOT NULL,
    location VARCHAR(255),
    slug VARCHAR(255),
    admission_status ENUM('admitted', 'embalmed', 'released', 'buried') DEFAULT 'admitted',
    release_status ENUM('pending', 'approved', 'released') DEFAULT 'pending',
    chamber_assigned VARCHAR(50),
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_deleted BOOLEAN DEFAULT FALSE,
    
    -- ADDING MISSING FIELDS (from your code):
    portal_slug VARCHAR(255) UNIQUE,
    status VARCHAR(50) DEFAULT 'active',
    total_mortuary_charge DECIMAL(10,2) DEFAULT 0.00,
    currency VARCHAR(3) DEFAULT 'KES',
    burial_type VARCHAR(50),
    dispatch_date DATE,
    
    PRIMARY KEY (id),
    UNIQUE KEY unique_deceased_id (deceased_id),
    UNIQUE KEY unique_admission_number (admission_number),
    UNIQUE KEY unique_national_id (national_id),
    UNIQUE KEY unique_portal_slug (portal_slug),
    INDEX idx_deceased_id (deceased_id),
    INDEX idx_national_id (national_id),
    INDEX idx_date_of_death (date_of_death),
    INDEX idx_admission_status (admission_status),
    INDEX idx_release_status (release_status),
    INDEX idx_created_at (created_at),
    INDEX idx_full_name (full_name),
    INDEX idx_status (status),
    
    FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Deceased persons';