const PDFDocument = require('pdfkit');
const ExcelJS = require('exceljs');
const AnalyticsModel = require('../models/analyticsModel');
const { Logger } = require('../../utilities/logger/logger');

class AnalyticsService {
  // Generate PDF report
  static async generatePDFReport(analyticsData, reportTitle = 'Analytics Report') {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ size: 'A4', margin: 50 });
        const chunks = [];

        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => {
          const pdfBuffer = Buffer.concat(chunks);
          resolve(pdfBuffer);
        });

        // Header
        doc.fontSize(24).font('Helvetica-Bold').text(reportTitle, { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica').text(new Date().toLocaleDateString(), { align: 'center' });
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(1);

        // KPIs
        if (analyticsData.kpis) {
          doc.fontSize(14).font('Helvetica-Bold').text('Key Performance Indicators');
          doc.moveDown(0.5);
          
          const kpiTable = [
            ['Metric', 'Value'],
            ['Total Cases', analyticsData.kpis.total_cases || 0],
            ['Released Cases', analyticsData.kpis.released_cases || 0],
            ['Total Revenue', `KES ${(analyticsData.kpis.total_revenue || 0).toLocaleString()}`],
            ['Avg Stay (Days)', (analyticsData.kpis.avg_stay_days || 0).toFixed(1)],
            ['Outstanding Balance', `KES ${(analyticsData.kpis.outstanding_balance || 0).toLocaleString()}`],
          ];

          doc.fontSize(10).table(kpiTable, {
            x: 50,
            y: doc.y,
            width: 500,
            rowHeight: 25,
          });

          doc.moveDown(1);
        }

        // Revenue Breakdown
        if (analyticsData.revenueByCategory && analyticsData.revenueByCategory.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Revenue Breakdown');
          doc.moveDown(0.5);

          const revenueTable = [
            ['Category', 'Amount (KES)'],
            ...analyticsData.revenueByCategory.map(item => [
              item.category,
              item.amount.toLocaleString()
            ])
          ];

          doc.fontSize(10).table(revenueTable, {
            x: 50,
            y: doc.y,
            width: 500,
            rowHeight: 20,
          });

          doc.moveDown(1);
        }

        // Case Distribution
        if (analyticsData.caseDistribution && analyticsData.caseDistribution.length > 0) {
          doc.fontSize(14).font('Helvetica-Bold').text('Case Distribution');
          doc.moveDown(0.5);

          const caseTable = [
            ['Status', 'Count', 'Percentage'],
            ...analyticsData.caseDistribution.map(item => [
              item.status,
              item.count,
              item.percentage + '%'
            ])
          ];

          doc.fontSize(10).table(caseTable, {
            x: 50,
            y: doc.y,
            width: 500,
            rowHeight: 20,
          });

          doc.moveDown(1);
        }

        // Footer
        doc.fontSize(8).text('Generated by Analytics System', 50, doc.page.height - 50, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  // Generate Excel report
  static async generateExcelReport(analyticsData, reportTitle = 'Analytics Report') {
    const workbook = new ExcelJS.Workbook();

    // Summary Sheet
    const summarySheet = workbook.addWorksheet('Summary');
    summarySheet.columns = [
      { header: 'Metric', key: 'metric', width: 30 },
      { header: 'Value', key: 'value', width: 20 },
    ];

    if (analyticsData.kpis) {
      summarySheet.addRows([
        { metric: 'Total Cases', value: analyticsData.kpis.total_cases || 0 },
        { metric: 'Released Cases', value: analyticsData.kpis.released_cases || 0 },
        { metric: 'Total Revenue', value: analyticsData.kpis.total_revenue || 0 },
        { metric: 'Avg Stay (Days)', value: (analyticsData.kpis.avg_stay_days || 0).toFixed(1) },
        { metric: 'Embalmed Cases', value: analyticsData.kpis.embalmed_cases || 0 },
        { metric: 'Outstanding Balance', value: analyticsData.kpis.outstanding_balance || 0 },
      ]);

      summarySheet.getRow(1).font = { bold: true, fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } }, color: { argb: 'FFFFFFFF' } };
    }

    // Revenue Sheet
    if (analyticsData.revenueByCategory && analyticsData.revenueByCategory.length > 0) {
      const revenueSheet = workbook.addWorksheet('Revenue');
      revenueSheet.columns = [
        { header: 'Category', key: 'category', width: 20 },
        { header: 'Amount (KES)', key: 'amount', width: 20 },
      ];
      revenueSheet.addRows(analyticsData.revenueByCategory);
      revenueSheet.getRow(1).font = { bold: true, fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } }, color: { argb: 'FFFFFFFF' } };
    }

    // Cases Sheet
    if (analyticsData.caseDistribution && analyticsData.caseDistribution.length > 0) {
      const casesSheet = workbook.addWorksheet('Cases');
      casesSheet.columns = [
        { header: 'Status', key: 'status', width: 20 },
        { header: 'Count', key: 'count', width: 15 },
        { header: 'Percentage', key: 'percentage', width: 15 },
      ];
      casesSheet.addRows(analyticsData.caseDistribution);
      casesSheet.getRow(1).font = { bold: true, fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } }, color: { argb: 'FFFFFFFF' } };
    }

    // Monthly Trends
    if (analyticsData.monthlyTrends && analyticsData.monthlyTrends.length > 0) {
      const trendsSheet = workbook.addWorksheet('Monthly Trends');
      trendsSheet.columns = [
        { header: 'Month', key: 'month', width: 15 },
        { header: 'Cases', key: 'cases', width: 12 },
        { header: 'Revenue', key: 'revenue', width: 15 },
        { header: 'Avg Stay', key: 'avg_stay_days', width: 12 },
      ];
      trendsSheet.addRows(analyticsData.monthlyTrends);
      trendsSheet.getRow(1).font = { bold: true, fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } }, color: { argb: 'FFFFFFFF' } };
    }

    return await workbook.xlsx.writeBuffer();
  }

  // Calculate monthly statistics
  static async calculateMonthlyStats(tenantId, month, year) {
    try {
      const [monthlyData] = await AnalyticsModel.getMonthlyAnalytics(tenantId, month, year);
      return monthlyData || {};
    } catch (error) {
      Logger.error('Error calculating monthly stats:', error);
      return {};
    }
  }

  // Calculate yearly statistics
  static async calculateYearlyStats(tenantId, year) {
    try {
      return await AnalyticsModel.getYearlyAnalytics(tenantId, year);
    } catch (error) {
      Logger.error('Error calculating yearly stats:', error);
      return [];
    }
  }

  // Get comprehensive dashboard data
  static async getDashboardData(tenantId, startDate, endDate) {
    try {
      const [kpis] = await AnalyticsModel.getKPIMetrics(tenantId, startDate, endDate);
      const revenueByCategory = await AnalyticsModel.getRevenueByCategory(tenantId, startDate, endDate);
      const caseDistribution = await AnalyticsModel.getCaseDistribution(tenantId, startDate, endDate);
      const dailyTrends = await AnalyticsModel.getDailyTrends(tenantId, startDate, endDate);
      const topServices = await AnalyticsModel.getTopServices(tenantId, startDate, endDate);

      return {
        kpis: kpis || {},
        revenueByCategory: revenueByCategory || [],
        caseDistribution: caseDistribution || [],
        dailyTrends: dailyTrends || [],
        topServices: topServices || [],
      };
    } catch (error) {
      Logger.error('Error getting dashboard data:', error);
      return {};
    }
  }

  // Get monthly trends
  static async getMonthlyTrends(tenantId, year) {
    try {
      return await AnalyticsModel.getYearlyAnalytics(tenantId, year);
    } catch (error) {
      Logger.error('Error getting monthly trends:', error);
      return [];
    }
  }

  // Export to CSV
  static async exportToCSV(analyticsData) {
    let csv = 'Analytics Report\n';
    csv += `Generated: ${new Date().toISOString()}\n\n`;

    if (analyticsData.kpis) {
      csv += 'Key Performance Indicators\n';
      csv += 'Metric,Value\n';
      Object.entries(analyticsData.kpis).forEach(([key, value]) => {
        csv += `${key},${value}\n`;
      });
      csv += '\n';
    }

    if (analyticsData.revenueByCategory) {
      csv += 'Revenue Breakdown\n';
      csv += 'Category,Amount\n';
      analyticsData.revenueByCategory.forEach(item => {
        csv += `${item.category},${item.amount}\n`;
      });
      csv += '\n';
    }

    return csv;
  }
}

module.exports = AnalyticsService;
